<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-6GHSNO6" name="com.lemon_yy.testcases.AddLoanTest" tests="25" failures="3" timestamp="2022-04-10T17:27:31 CST" time="2.874" errors="0">
  <testcase name="testAddLoan" time="0.116" classname="com.lemon_yy.testcases.AddLoanTest"/>
  <testcase name="testAddLoan" time="0.116" classname="com.lemon_yy.testcases.AddLoanTest">
    <failure type="java.lang.AssertionError" message="接口响应断言失败 expected [10] but found [5]">
      <![CDATA[java.lang.AssertionError: 接口响应断言失败 expected [10] but found [5]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at com.lemon_yy.base.BaseCase.assertExpected(BaseCase.java:132)
at com.lemon_yy.testcases.AddLoanTest.testAddLoan(AddLoanTest.java:52)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
    </failure>
  </testcase> <!-- testAddLoan -->
  <testcase name="testAddLoan" time="0.123" classname="com.lemon_yy.testcases.AddLoanTest">
    <failure type="java.lang.AssertionError" message="接口响应断言失败 expected [2] but found [5]">
      <![CDATA[java.lang.AssertionError: 接口响应断言失败 expected [2] but found [5]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at com.lemon_yy.base.BaseCase.assertExpected(BaseCase.java:132)
at com.lemon_yy.testcases.AddLoanTest.testAddLoan(AddLoanTest.java:52)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
    </failure>
  </testcase> <!-- testAddLoan -->
  <testcase name="testAddLoan" time="0.144" classname="com.lemon_yy.testcases.AddLoanTest"/>
  <testcase name="testAddLoan" time="0.132" classname="com.lemon_yy.testcases.AddLoanTest"/>
  <testcase name="testAddLoan" time="0.084" classname="com.lemon_yy.testcases.AddLoanTest"/>
  <testcase name="testAddLoan" time="0.162" classname="com.lemon_yy.testcases.AddLoanTest"/>
  <testcase name="testAddLoan" time="0.115" classname="com.lemon_yy.testcases.AddLoanTest"/>
  <testcase name="testAddLoan" time="0.101" classname="com.lemon_yy.testcases.AddLoanTest"/>
  <testcase name="testAddLoan" time="0.100" classname="com.lemon_yy.testcases.AddLoanTest"/>
  <testcase name="testAddLoan" time="0.100" classname="com.lemon_yy.testcases.AddLoanTest"/>
  <testcase name="testAddLoan" time="0.116" classname="com.lemon_yy.testcases.AddLoanTest"/>
  <testcase name="testAddLoan" time="0.131" classname="com.lemon_yy.testcases.AddLoanTest">
    <failure type="java.lang.AssertionError" message="接口响应断言失败 expected [1] but found [5]">
      <![CDATA[java.lang.AssertionError: 接口响应断言失败 expected [1] but found [5]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at com.lemon_yy.base.BaseCase.assertExpected(BaseCase.java:132)
at com.lemon_yy.testcases.AddLoanTest.testAddLoan(AddLoanTest.java:52)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
    </failure>
  </testcase> <!-- testAddLoan -->
  <testcase name="testAddLoan" time="0.104" classname="com.lemon_yy.testcases.AddLoanTest"/>
  <testcase name="testAddLoan" time="0.116" classname="com.lemon_yy.testcases.AddLoanTest"/>
  <testcase name="testAddLoan" time="0.100" classname="com.lemon_yy.testcases.AddLoanTest"/>
  <testcase name="testAddLoan" time="0.138" classname="com.lemon_yy.testcases.AddLoanTest"/>
  <testcase name="testAddLoan" time="0.123" classname="com.lemon_yy.testcases.AddLoanTest"/>
  <testcase name="testAddLoan" time="0.115" classname="com.lemon_yy.testcases.AddLoanTest"/>
  <testcase name="testAddLoan" time="0.100" classname="com.lemon_yy.testcases.AddLoanTest"/>
  <testcase name="testAddLoan" time="0.101" classname="com.lemon_yy.testcases.AddLoanTest"/>
  <testcase name="testAddLoan" time="0.122" classname="com.lemon_yy.testcases.AddLoanTest"/>
  <testcase name="testAddLoan" time="0.099" classname="com.lemon_yy.testcases.AddLoanTest"/>
  <testcase name="testAddLoan" time="0.116" classname="com.lemon_yy.testcases.AddLoanTest"/>
  <testcase name="testAddLoan" time="0.100" classname="com.lemon_yy.testcases.AddLoanTest"/>
</testsuite> <!-- com.lemon_yy.testcases.AddLoanTest -->
